-- ============================================
-- INTERNAL ADVERTISING SYSTEM
-- System-intelligence generated ads + admin overrides
-- ============================================

CREATE TABLE IF NOT EXISTS internal_ads (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  
  -- Content
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  cta_text TEXT NOT NULL DEFAULT 'Learn More',
  cta_link TEXT NOT NULL DEFAULT '/',
  
  -- Targeting
  target_audience TEXT NOT NULL DEFAULT 'all' CHECK (target_audience IN ('all', 'client', 'freelancer', 'guest')),
  
  -- Display
  ad_type TEXT NOT NULL DEFAULT 'card' CHECK (ad_type IN ('card', 'banner', 'highlight')),
  icon TEXT, -- lucide icon name
  color_scheme TEXT DEFAULT 'green' CHECK (color_scheme IN ('green', 'blue', 'purple', 'amber', 'red', 'gray')),
  image_url TEXT,
  
  -- Priority & scheduling
  priority INTEGER DEFAULT 0, -- higher = shown first
  is_active BOOLEAN DEFAULT true,
  is_system_generated BOOLEAN DEFAULT false, -- true = auto-generated by system intelligence
  start_date TIMESTAMPTZ,
  end_date TIMESTAMPTZ,
  
  -- Stats
  impressions INTEGER DEFAULT 0,
  clicks INTEGER DEFAULT 0,
  
  -- Metadata
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE internal_ads ENABLE ROW LEVEL SECURITY;

-- Everyone can view active ads
CREATE POLICY "Active ads are viewable by everyone"
  ON internal_ads FOR SELECT
  USING (is_active = true);

-- Only admins can manage ads
CREATE POLICY "Admins can manage ads"
  ON internal_ads FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE user_id = auth.uid() AND role = 'Admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE user_id = auth.uid() AND role = 'Admin')
  );

-- Index for fast lookups
CREATE INDEX idx_internal_ads_active ON internal_ads(is_active, priority DESC);
CREATE INDEX idx_internal_ads_audience ON internal_ads(target_audience, is_active);
CREATE INDEX idx_internal_ads_dates ON internal_ads(start_date, end_date) WHERE is_active = true;
